import type { PlayerStats } from "../Player";

export const playerMock: PlayerStats[] = [
    { name: "Shai Gilgeous-Alexander", points: 32, assists: 6, rebounds: 5 },
    { name: "Giannis Antetokounmpo", points: 31, assists: 6, rebounds: 12 },
    { name: "Nikola Jokić", points: 29, assists: 11, rebounds: 13 },
    { name: "Anthony Edwards", points: 27, assists: 5, rebounds: 6 },
    { name: "Jayson Tatum", points: 27, assists: 6, rebounds: 9 },
    { name: "Luka Dončić", points: 26, assists: 8, rebounds: 8 },
    { name: "Donovan Mitchell", points: 26, assists: 5, rebounds: 4 },
    { name: "Joel Embiid", points: 25, assists: 4, rebounds: 11 },
    { name: "Devin Booker", points: 25, assists: 6, rebounds: 4 },
    { name: "Damian Lillard", points: 24, assists: 7, rebounds: 4 },
    { name: "Trae Young", points: 24, assists: 10, rebounds: 4 },
    { name: "Stephen Curry", points: 23, assists: 6, rebounds: 5 },
    { name: "Jaylen Brown", points: 23, assists: 4, rebounds: 7 },
    { name: "Kevin Durant", points: 22, assists: 4, rebounds: 6 },
    { name: "LeBron James", points: 22, assists: 8, rebounds: 8 },
    { name: "Jalen Brunson", points: 22, assists: 7, rebounds: 3 },
    { name: "DeMar DeRozan", points: 21, assists: 4, rebounds: 4 },
    { name: "Pascal Siakam", points: 21, assists: 3, rebounds: 7 },
    { name: "Kyrie Irving", points: 20, assists: 5, rebounds: 4 },
    { name: "Anthony Davis", points: 20, assists: 3, rebounds: 11 },
    { name: "Tyrese Haliburton", points: 19, assists: 9, rebounds: 4 },
    { name: "Alperen Şengün", points: 19, assists: 4, rebounds: 10 },
    { name: "Karl-Anthony Towns", points: 19, assists: 3, rebounds: 9 },
    { name: "Ja Morant", points: 18, assists: 7, rebounds: 5 },
    { name: "Zion Williamson", points: 18, assists: 4, rebounds: 7 },
    { name: "De’Aaron Fox", points: 18, assists: 6, rebounds: 4 },
    { name: "Brandon Ingram", points: 17, assists: 4, rebounds: 6 },
    { name: "Julius Randle", points: 17, assists: 3, rebounds: 8 },
    { name: "C.J. McCollum", points: 17, assists: 4, rebounds: 3 },
    { name: "Paul George", points: 16, assists: 4, rebounds: 5 },
    { name: "Kawhi Leonard", points: 16, assists: 3, rebounds: 6 },
    { name: "Victor Wembanyama", points: 16, assists: 2, rebounds: 9 },
    { name: "Myles Turner", points: 15, assists: 1, rebounds: 7 },
    { name: "Domantas Sabonis", points: 15, assists: 6, rebounds: 11 },
    { name: "Aaron Jones", points: 15, assists: 2, rebounds: 6 },
    { name: "Nikola Vučević", points: 14, assists: 2, rebounds: 9 },
    { name: "Jaren Jackson Jr.", points: 14, assists: 1, rebounds: 6 },
    { name: "Fred VanVleet", points: 13, assists: 6, rebounds: 3 },
    { name: "Darius Garland", points: 13, assists: 5, rebounds: 2 },
    { name: "Tyler Herro", points: 13, assists: 3, rebounds: 4 },
    { name: "Dejounte Murray", points: 12, assists: 5, rebounds: 5 },
    { name: "Bam Adebayo", points: 12, assists: 3, rebounds: 10 },
    { name: "Jarrett Allen", points: 11, assists: 2, rebounds: 9 },
    { name: "Rudy Gobert", points: 11, assists: 1, rebounds: 12 },
    { name: "Clint Capela", points: 10, assists: 1, rebounds: 8 },
    { name: "Jonas Valančiūnas", points: 10, assists: 2, rebounds: 7 },
    { name: "Josh Giddey", points: 9, assists: 5, rebounds: 6 },
    { name: "Cade Cunningham", points: 9, assists: 6, rebounds: 5 },
    { name: "Scoot Henderson", points: 8, assists: 4, rebounds: 3 },
    { name: "Jalen Green", points: 7, assists: 2, rebounds: 3 },
    { name: "Patrick Baldwin Jr.", points: 5, assists: 1, rebounds: 2 },
    { name: "Theo Maledon", points: 4, assists: 2, rebounds: 3 },
    { name: "Trey Murphy III", points: 4, assists: 1, rebounds: 1 },
    { name: "Austin Reaves", points: 4, assists: 2, rebounds: 2 },
    { name: "Jevon Carter", points: 3, assists: 1, rebounds: 1 },
    { name: "Killian Hayes", points: 3, assists: 2, rebounds: 1 },
    { name: "Ousmane Dieng", points: 3, assists: 1, rebounds: 2 },
    { name: "Frank Ntilikina", points: 2, assists: 2, rebounds: 1 },
    { name: "Udoka Azubuike", points: 2, assists: 0, rebounds: 2 },
    { name: "Ty Jerome", points: 2, assists: 1, rebounds: 1 },
    { name: "Dylan Windler", points: 2, assists: 0, rebounds: 1 },
    { name: "James Bouknight", points: 1, assists: 0, rebounds: 1 },
    { name: "Romeo Langford", points: 1, assists: 0, rebounds: 0 },
    { name: "Goga Bitadze", points: 1, assists: 0, rebounds: 2 },
    { name: "Darius Bazley", points: 1, assists: 0, rebounds: 1 },
    { name: "Isaiah Todd", points: 0, assists: 0, rebounds: 1 },
    { name: "Sekou Doumbouya", points: 0, assists: 0, rebounds: 0 }
];